/*
 * Copyright (c) 2022 Tommy Ettinger.
 * The parent project is
 * https://github.com/tommyettinger/game-icons-net-atlas
 * Licensed identically to Game-Icons.net's images; for the list of contributors who must be credited, see:
 * https://github.com/tommyettinger/game-icons-net-atlas/blob/main/Game-Icons-License.txt
 */

package com.github.tommyettinger;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;

/**
 * On Windows, to resize the many 512x512 PNG files to 60x60:
 * {@code FOR /R %i IN (*.png) DO magick mogrify -resize 60x60 %i} (from inside assembler/assets/)
 * Then...
 * {@code oxipng -o 6 -s --ng *.png} (from inside docs/flat/)
 */
public class Main extends ApplicationAdapter {
    @Override
    public void create() {
        StringBuilder sb = new StringBuilder(4096);
        sb.append("""
                <!doctype html>
                <html>
                <head>
                \t<title>Game-Icons.net Preview</title>
                \t<meta http-equiv="content-type" content="text/html; charset=UTF-8">
                \t<meta id="gameViewport" name="viewport" content="width=device-width initial-scale=1">
                \t<link href="styles.css" rel="stylesheet" type="text/css">
                </head>
                
                """);
        sb.append("<body>\n");
        sb.append("<h1>Game-Icons.Net Preview</h1>\n");
        sb.append("<p>This shows all icons supported by " +
                  "<a href=\"https://github.com/tommyettinger/game-icons-net-atlas\">game-icons-net-atlas</a>, " +
                  "along with the two names each can be looked up by.</p>\n");
        sb.append("""
                <p>The atlases and all image assets are licensed under CC-BY 3.0 (some are individually licensed as CC0,
                  which doesn't affect the complete atlas; it's still CC-BY 3.0). The icons here were made by:</p>
                <ul>
                  <li>Lorc, <a href="http://lorcblog.blogspot.com">http://lorcblog.blogspot.com</a></li>
                  <li>Delapouite, <a href="https://delapouite.com">https://delapouite.com</a></li>
                  <li>John Colburn, <a href="http://ninmunanmu.com">http://ninmunanmu.com</a></li>
                  <li>Felbrigg, <a href="http://blackdogofdoom.blogspot.co.uk">http://blackdogofdoom.blogspot.co.uk</a></li>
                  <li>John Redman, <a href="http://www.uniquedicetowers.com">http://www.uniquedicetowers.com</a></li>
                  <li>Carl Olsen, <a href="https://twitter.com/unstoppableCarl">https://twitter.com/unstoppableCarl</a></li>
                  <li>Sbed, <a href="http://opengameart.org/content/95-game-icons">http://opengameart.org/content/95-game-icons</a></li>
                  <li>PriorBlue</li>
                  <li>Willdabeast, <a href="http://wjbstories.blogspot.com">http://wjbstories.blogspot.com</a></li>
                  <li>Viscious Speed, <a href="http://viscious-speed.deviantart.com">http://viscious-speed.deviantart.com</a></li>
                  <li>Lord Berandas, <a href="http://berandas.deviantart.com">http://berandas.deviantart.com</a></li>
                  <li>Irongamer, <a href="http://ecesisllc.wix.com/home">http://ecesisllc.wix.com/home</a></li>
                  <li>HeavenlyDog, <a href="http://www.gnomosygoblins.blogspot.com">http://www.gnomosygoblins.blogspot.com</a></li>
                  <li>Lucas</li>
                  <li>Faithtoken, <a href="http://fungustoken.deviantart.com">http://fungustoken.deviantart.com</a></li>
                  <li>Skoll</li>
                  <li>Andy Meneely, <a href="http://www.se.rit.edu/~andy/">http://www.se.rit.edu/~andy/</a></li>
                  <li>Cathelineau</li>
                  <li>Kier Heyl</li>
                  <li>Aussiesim</li>
                  <li>Sparker, <a href="http://citizenparker.com">http://citizenparker.com</a></li>
                  <li>Zeromancer</li>
                  <li>Rihlsul</li>
                  <li>Quoting</li>
                  <li>Guard13007, <a href="https://guard13007.com">https://guard13007.com</a></li>
                  <li>DarkZaitzev, <a href="http://darkzaitzev.deviantart.com">http://darkzaitzev.deviantart.com</a></li>
                  <li>SpencerDub</li>
                  <li>GeneralAce135</li>
                  <li>Zajkonur</li>
                  <li>Catsu</li>
                  <li>Starseeker</li>
                  <li>Pepijn Poolman</li>
                  <li>Pierre Leducq</li>
                  <li>Caro Asercion</li>
                </ul>
                <p>(Projects that use this atlas can copy the above list of Game-Icons.net contributors to comply with
                  its license.)</p>
                """);
        sb.append("<div class=\"box\">\n");
        for(String name : allNames){
            String iconFile = "flat/" + name + ".png";
            sb.append("\t<div class=\"item\">\n")
                    .append("\t\t<img src=\"")
                    .append(iconFile).append("\" alt=\"").append(name).append("\" />\n")
                    .append("\t\t<p>").append(name).append("</p>\n")
                    .append("\t</div>\n");
        }
        sb.append("</div>\n</body>\n");
        sb.append("</html>\n");
        Gdx.files.local("index.html").writeString(sb.toString(), false, "UTF8");
    }

    /**
     * Generated with:
     * <br>
     * {@code ls -m -Q --color=never docs/flat/ > all-names.txt }
     */
    public static String[] allNames = new String[]{
            "3d-glasses.png", "3d-hammer.png", "3d-meeple.png", "3d-stairs.png",
            "abacus.png", "abbot-meeple.png", "abdominal-armor.png", "abstract-001.png",
            "abstract-002.png", "abstract-003.png", "abstract-004.png", "abstract-005.png",
            "abstract-006.png", "abstract-007.png", "abstract-008.png", "abstract-009.png",
            "abstract-010.png", "abstract-011.png", "abstract-012.png", "abstract-013.png",
            "abstract-014.png", "abstract-015.png", "abstract-016.png", "abstract-017.png",
            "abstract-018.png", "abstract-019.png", "abstract-020.png", "abstract-021.png",
            "abstract-022.png", "abstract-023.png", "abstract-024.png", "abstract-025.png",
            "abstract-026.png", "abstract-027.png", "abstract-028.png", "abstract-029.png",
            "abstract-030.png", "abstract-031.png", "abstract-032.png", "abstract-033.png",
            "abstract-034.png", "abstract-035.png", "abstract-036.png", "abstract-037.png",
            "abstract-038.png", "abstract-039.png", "abstract-040.png", "abstract-041.png",
            "abstract-042.png", "abstract-043.png", "abstract-044.png", "abstract-045.png",
            "abstract-046.png", "abstract-047.png", "abstract-048.png", "abstract-049.png",
            "abstract-050.png", "abstract-051.png", "abstract-052.png", "abstract-053.png",
            "abstract-054.png", "abstract-055.png", "abstract-056.png", "abstract-057.png",
            "abstract-058.png", "abstract-059.png", "abstract-060.png", "abstract-061.png",
            "abstract-062.png", "abstract-063.png", "abstract-064.png", "abstract-065.png",
            "abstract-066.png", "abstract-067.png", "abstract-068.png", "abstract-069.png",
            "abstract-070.png", "abstract-071.png", "abstract-072.png", "abstract-073.png",
            "abstract-074.png", "abstract-075.png", "abstract-076.png", "abstract-077.png",
            "abstract-078.png", "abstract-079.png", "abstract-080.png", "abstract-081.png",
            "abstract-082.png", "abstract-083.png", "abstract-084.png", "abstract-085.png",
            "abstract-086.png", "abstract-087.png", "abstract-088.png", "abstract-089.png",
            "abstract-090.png", "abstract-091.png", "abstract-092.png", "abstract-093.png",
            "abstract-094.png", "abstract-095.png", "abstract-096.png", "abstract-097.png",
            "abstract-098.png", "abstract-099.png", "abstract-100.png", "abstract-101.png",
            "abstract-102.png", "abstract-103.png", "abstract-104.png", "abstract-105.png",
            "abstract-106.png", "abstract-107.png", "abstract-108.png", "abstract-109.png",
            "abstract-110.png", "abstract-111.png", "abstract-112.png", "abstract-113.png",
            "abstract-114.png", "abstract-115.png", "abstract-116.png", "abstract-117.png",
            "abstract-118.png", "abstract-119.png", "abstract-120.png", "abstract-121.png",
            "accordion.png", "ace.png", "achievement.png", "achilles-heel.png",
            "acid-blob.png", "acid-shield.png", "acid-tube.png", "acid.png", "acorn.png",
            "acoustic-megaphone.png", "acrobatic.png", "aerial-signal.png", "aero-bike.png",
            "aerodynamic-harpoon.png", "aerosol.png", "africa.png", "afterburn.png",
            "agave.png", "ages.png", "air-balloon.png", "air-force.png", "air-man.png",
            "air-zigzag.png", "airplane-arrival.png", "airplane-departure.png",
            "airplane.png", "airtight-hatch.png", "ak47.png", "ak47u.png", "akhet.png",
            "alarm-clock.png", "algae.png", "algeria.png", "alien-bug.png", "alien-egg.png",
            "alien-fire.png", "alien-skull.png", "alien-stare.png", "all-for-one.png",
            "all-seeing-eye.png", "allied-star.png", "alligator-clip.png", "almond.png",
            "amber-mosquito.png", "ambulance.png", "american-football-ball.png",
            "american-football-helmet.png", "american-football-player.png",
            "american-shield.png", "amethyst.png", "ammo-box.png", "ammonite-fossil.png",
            "ammonite.png", "amphora.png", "ample-dress.png", "amplitude.png",
            "amputation.png", "anarchy.png", "anatomy.png", "anchor.png",
            "ancient-columns.png", "ancient-ruins.png", "ancient-screw.png",
            "ancient-sword.png", "android-mask.png", "andromeda-chain.png",
            "angel-outfit.png", "angel-wings.png", "angler-fish.png", "angola.png",
            "angry-eyes.png", "angular-spider.png", "animal-hide.png", "animal-skull.png",
            "ankh.png", "annexation.png", "ant.png", "antarctica.png", "anteater.png",
            "anthem.png", "anti-aircraft-gun.png", "antibody.png",
            "anticlockwise-rotation.png", "ants.png", "anubis.png", "anvil-impact.png",
            "anvil.png", "apc.png", "apollo-capsule.png", "apothecary.png",
            "apple-core.png", "apple-maggot.png", "apple-seeds.png", "aquarium.png",
            "aquarius.png", "aqueduct.png", "arabic-door.png", "arc-triomphe.png",
            "arch-bridge.png", "archaeopteryx-fossil.png", "archer.png",
            "archery-target.png", "architect-mask.png", "archive-register.png",
            "archive-research.png", "arcing-bolt.png", "arena.png", "aries.png",
            "arm-bandage.png", "arm-sling.png", "arm.png", "armadillo-tail.png",
            "armadillo.png", "armchair.png", "armor-blueprint.png", "armor-cuisses.png",
            "armor-downgrade.png", "armor-punch.png", "armor-upgrade.png", "armor-vest.png",
            "armored-boomerang.png", "armored-pants.png", "armoured-shell.png",
            "arrest.png", "arrow-cluster.png", "arrow-cursor.png", "arrow-dunk.png",
            "arrow-flights.png", "arrow-scope.png", "arrow-wings.png", "arrowed.png",
            "arrowhead.png", "arrows-shield.png", "arson.png", "artichoke.png",
            "artificial-hive.png", "artificial-intelligence.png", "artillery-shell.png",
            "ascending-block.png", "asian-lantern.png", "asparagus.png", "aspergillum.png",
            "assassin-pocket.png", "asteroid.png", "astrolabe.png", "astronaut-helmet.png",
            "at-sea.png", "atlas.png", "atom-core.png", "atom.png", "atomic-slashes.png",
            "attached-shield.png", "attack-gauge.png", "aubergine.png",
            "audio-cassette.png", "aura.png", "australia.png", "auto-repair.png",
            "autogun.png", "automatic-sas.png", "avocado.png", "avoidance.png",
            "awareness.png", "axe-in-log.png", "axe-in-stump.png", "axe-swing.png",
            "axe-sword.png", "axolotl.png", "aztec-calendar-sun.png", "azul-flake.png",
            "baby-bottle.png", "baby-face.png", "babyfoot-players.png", "back-forth.png",
            "back-pain.png", "backbone-shell.png", "backgammon.png", "backpack.png",
            "backstab.png", "backup.png", "backward-time.png", "bacon.png",
            "bad-breath.png", "bad-gnome.png", "badger.png", "bagpipes.png",
            "balaclava.png", "balkenkreuz.png", "ball-glow.png", "ball-heart.png",
            "ball-pyramid.png", "ballerina-shoes.png", "ballista.png", "balloon-dog.png",
            "balloons.png", "bamboo-fountain.png", "bamboo.png", "banana-bunch.png",
            "banana-peel.png", "banana-peeled.png", "banana.png", "bandage-roll.png",
            "bandaged.png", "bandana.png", "bandit.png", "banging-gavel.png", "banjo.png",
            "bank.png", "banknote.png", "baobab.png", "bar-stool.png", "barbarian.png",
            "barbecue.png", "barbed-arrow.png", "barbed-coil.png", "barbed-nails.png",
            "barbed-spear.png", "barbed-star.png", "barbed-sun.png", "barbed-wire.png",
            "barbute.png", "barefoot.png", "barn-owl.png", "barn.png", "barracks-tent.png",
            "barracks.png", "barrel-leak.png", "barrel.png", "barricade.png", "barrier.png",
            "base-dome.png", "baseball-bat.png", "baseball-glove.png", "basket.png",
            "basketball-ball.png", "basketball-basket.png", "basketball-jersey.png",
            "basset-hound-head.png", "bassoon.png", "bastet.png", "bat-alt.png",
            "bat-blade.png", "bat-leth.png", "bat-mask.png", "bat-wing.png", "bat.png",
            "bathtub.png", "baton.png", "battered-axe.png", "batteries.png",
            "battery-0.png", "battery-100.png", "battery-25.png", "battery-50.png",
            "battery-75.png", "battery-minus.png", "battery-pack-alt.png",
            "battery-pack.png", "battery-plus.png", "battle-axe.png", "battle-gear.png",
            "battle-mech.png", "battle-tank.png", "battleship.png", "batwing-emblem.png",
            "bayonet.png", "beach-bag.png", "beach-ball.png", "beach-bucket.png",
            "beam-satellite.png", "beam-wake.png", "beams-aura.png", "beanstalk.png",
            "bear-face.png", "bear-head.png", "beard.png", "beast-eye.png", "beaver.png",
            "bed-lamp.png", "bed.png", "bee.png", "beech.png", "beehive.png",
            "beer-bottle.png", "beer-horn.png", "beer-stein.png", "beet.png",
            "beetle-shell.png", "behold.png", "belgium.png", "bell-pepper.png",
            "bell-shield.png", "bellows.png", "belt-armor.png", "belt-buckles.png",
            "belt.png", "berries-bowl.png", "berry-bush.png", "bestial-fangs.png",
            "beveled-star.png", "biceps.png", "big-diamond-ring.png", "big-egg.png",
            "big-gear.png", "big-wave.png", "billed-cap.png", "bindle.png",
            "binoculars.png", "biohazard.png", "biplane.png", "birch-trees.png",
            "bird-cage.png", "bird-claw.png", "bird-house.png", "bird-limb.png",
            "bird-mask.png", "bird-scepter.png", "bird-twitter.png", "bison.png",
            "black-bar.png", "black-belt.png", "black-book.png", "black-bridge.png",
            "black-flag.png", "black-hand-shield.png", "black-hole-bolas.png",
            "black-knight-helm.png", "black-sea.png", "blackball.png", "blackcurrant.png",
            "blacksmith.png", "blade-bite.png", "blade-drag.png", "blade-fall.png",
            "blanket.png", "blast.png", "blaster.png", "bleeding-eye.png",
            "bleeding-heart.png", "bleeding-wound.png", "blender.png", "blindfold.png",
            "block-house.png", "blood.png", "bloody-stash.png", "bloody-sword.png",
            "blunderbuss.png", "bo.png", "boar-ensign.png", "boar-tusks.png", "boar.png",
            "boarding-pass.png", "boat-engine.png", "boat-fishing.png", "boat-horizon.png",
            "boat-propeller.png", "boba.png", "body-balance.png", "body-height.png",
            "body-swapping.png", "boiling-bubbles.png", "bok-choy.png", "bolas.png",
            "bolivia.png", "bolt-bomb.png", "bolt-cutter.png", "bolt-drop.png",
            "bolt-eye.png", "bolt-saw.png", "bolt-shield.png", "bolt-spell-cast.png",
            "bolter-gun.png", "bomber.png", "bombing-run.png", "bone-gnawer.png",
            "bone-knife-alt.png", "bone-knife.png", "bone-mace.png", "bonsai-tree.png",
            "book-aura.png", "book-cover-alt.png", "book-cover.png", "book-pile.png",
            "book-storm.png", "bookmark.png", "bookmarklet.png", "bookshelf.png",
            "boombox.png", "boomerang-cross.png", "boomerang-sun.png", "boomerang.png",
            "boot-kick.png", "boot-prints.png", "boot-stomp.png", "boots.png", "booze.png",
            "bordered-shield.png", "boss-key.png", "bottle-cap.png", "bottle-vapors.png",
            "bottled-bolt.png", "bottled-shadow.png", "bottom-right-3d-arrow.png",
            "boulder-dash.png", "bouncing-spring.png", "bouncing-sword.png",
            "bow-arrow.png", "bow-string.png", "bow-tie-ribbon.png", "bow-tie.png",
            "bowels.png", "bowen-knot.png", "bowie-knife-alt.png", "bowie-knife.png",
            "bowl-of-rice.png", "bowl-spiral.png", "bowling-alley.png", "bowling-pin.png",
            "bowling-propulsion.png", "bowling-strike.png", "bowman.png", "box-cutter.png",
            "box-trap.png", "box-unpacking.png", "boxing-glove-surprise.png",
            "boxing-glove.png", "boxing-ring.png", "bracer.png", "bracers.png",
            "brain-dump.png", "brain-freeze.png", "brain-leak.png", "brain-stem.png",
            "brain-tentacle.png", "brain.png", "brainstorm.png", "branch-arrow.png",
            "brandy-bottle.png", "brasero.png", "brass-eye.png", "brass-knuckles.png",
            "brazil-flag.png", "brazil.png", "bread-slice.png", "bread.png",
            "breaking-chain.png", "breastplate.png", "brick-pile.png", "brick-wall.png",
            "bridge.png", "briefcase.png", "bright-explosion.png", "broad-dagger.png",
            "broadhead-arrow.png", "broadsword.png", "broccoli.png", "brodie-helmet.png",
            "broken-arrow.png", "broken-axe.png", "broken-bone.png", "broken-bottle.png",
            "broken-heart-zone.png", "broken-heart.png", "broken-pottery.png",
            "broken-ribbon.png", "broken-shield.png", "broken-skull.png",
            "broken-tablet.png", "broken-wall.png", "broom.png", "brutal-helm.png",
            "brute.png", "bubble-field.png", "bubbles.png", "bubbling-beam.png",
            "bubbling-bowl.png", "bubbling-flask.png", "bucket-wheel-excavator.png",
            "bud.png", "buffalo-head.png", "bug-net.png", "bugle-call.png", "bulb.png",
            "bulgaria.png", "bull-horns.png", "bull.png", "bulldozer.png",
            "bullet-bill.png", "bullet-impacts.png", "bullets.png", "bullseye.png",
            "bully-minion.png", "bundle-grenade.png", "bunk-beds.png", "bunker-assault.png",
            "bunker.png", "bunny-slippers.png", "buoy.png", "burn.png", "burning-blobs.png",
            "burning-book.png", "burning-dot.png", "burning-embers.png", "burning-eye.png",
            "burning-forest.png", "burning-meteor.png", "burning-passion.png",
            "burning-round-shot.png", "burning-skull.png", "burning-tree.png",
            "burst-blob.png", "bus-doors.png", "bus-stop.png", "bus.png",
            "butter-toast.png", "butter.png", "butterfly-flower.png",
            "butterfly-knife-alt.png", "butterfly-knife.png", "butterfly-warning.png",
            "butterfly.png", "button-finger.png", "buy-card.png", "byzantin-temple.png",
            "c96.png", "cabbage.png", "cable-stayed-bridge.png", "cactus-pot.png",
            "cactus-tap.png", "cactus.png", "cadillac-helm.png", "caduceus.png",
            "caesar.png", "cage.png", "caged-ball.png", "cake-slice.png", "calavera.png",
            "calculator.png", "caldera.png", "calendar-half-year.png", "calendar.png",
            "caltrops.png", "camargue-cross.png", "cambodia.png", "camel-head.png",
            "camel.png", "camp-cooking-pot.png", "campfire.png", "camping-tent.png",
            "canadian-goose.png", "cancel.png", "cancer.png", "candle-flame.png",
            "candle-holder.png", "candle-light.png", "candle-skull.png", "candlebright.png",
            "candles.png", "candlestick-phone.png", "candy-canes.png", "canned-fish.png",
            "cannister.png", "cannon-ball.png", "cannon-shot.png", "cannon.png",
            "canoe.png", "cantua.png", "cape-armor.png", "cape.png", "capitol.png",
            "capricorn.png", "captain-hat-profile.png", "capybara.png", "car-battery.png",
            "car-door.png", "car-key.png", "car-seat.png", "car-wheel.png", "carabiner.png",
            "carambola.png", "caravan.png", "caravel.png", "card-10-clubs.png",
            "card-10-diamonds.png", "card-10-hearts.png", "card-10-spades.png",
            "card-2-clubs.png", "card-2-diamonds.png", "card-2-hearts.png",
            "card-2-spades.png", "card-3-clubs.png", "card-3-diamonds.png",
            "card-3-hearts.png", "card-3-spades.png", "card-4-clubs.png",
            "card-4-diamonds.png", "card-4-hearts.png", "card-4-spades.png",
            "card-5-clubs.png", "card-5-diamonds.png", "card-5-hearts.png",
            "card-5-spades.png", "card-6-clubs.png", "card-6-diamonds.png",
            "card-6-hearts.png", "card-6-spades.png", "card-7-clubs.png",
            "card-7-diamonds.png", "card-7-hearts.png", "card-7-spades.png",
            "card-8-clubs.png", "card-8-diamonds.png", "card-8-hearts.png",
            "card-8-spades.png", "card-9-clubs.png", "card-9-diamonds.png",
            "card-9-hearts.png", "card-9-spades.png", "card-ace-clubs.png",
            "card-ace-diamonds.png", "card-ace-hearts.png", "card-ace-spades.png",
            "card-burn.png", "card-discard.png", "card-draw.png", "card-exchange.png",
            "card-jack-clubs.png", "card-jack-diamonds.png", "card-jack-hearts.png",
            "card-jack-spades.png", "card-joker.png", "card-king-clubs.png",
            "card-king-diamonds.png", "card-king-hearts.png", "card-king-spades.png",
            "card-pick.png", "card-pickup.png", "card-play.png", "card-queen-clubs.png",
            "card-queen-diamonds.png", "card-queen-hearts.png", "card-queen-spades.png",
            "card-random.png", "cardboard-box-closed.png", "cardboard-box.png",
            "cargo-crane.png", "cargo-crate.png", "cargo-ship.png", "carillon.png",
            "carnival-mask.png", "carnivore-mouth.png", "carnivorous-plant.png",
            "carnyx.png", "carousel.png", "carpet-bombing.png", "carrier.png",
            "carrion.png", "carrot.png", "cartwheel.png", "cash.png", "cassowary-head.png",
            "castle-alt.png", "castle-ruins.png", "castle.png", "cat.png", "catapult.png",
            "catch.png", "caterpillar.png", "cauldron-alt.png", "cauldron.png",
            "cavalry.png", "cave-entrance.png", "caveman.png", "cctv-camera.png",
            "ceiling-barnacle.png", "ceiling-light.png", "celebration-fire.png",
            "cellar-barrels.png", "cement-shoes.png", "centaur-heart.png", "centaur.png",
            "centipede.png", "centurion-helmet.png", "ceremonial-mask.png",
            "chain-lightning.png", "chain-mail.png", "chained-arrow-heads.png",
            "chained-heart.png", "chaingun.png", "chainsaw.png", "chakram.png",
            "chalice-drops.png", "chalk-outline-murder.png", "chameleon-glyph.png",
            "champagne-cork.png", "champions.png", "chanterelles.png", "character.png",
            "charcuterie.png", "charged-arrow.png", "charging-bull.png", "charging.png",
            "chariot.png", "charm.png", "chart.png", "chat-bubble.png", "check-mark.png",
            "checkbox-tree.png", "checked-shield.png", "checkered-diamond.png",
            "checkered-flag.png", "checklist.png", "cheerful.png", "cheese-wedge.png",
            "chef-toque.png", "chelsea-boot.png", "chemical-arrow.png", "chemical-bolt.png",
            "chemical-drop.png", "chemical-tank.png", "cherish.png", "cherry.png",
            "chess-bishop.png", "chess-king.png", "chess-knight.png", "chess-pawn.png",
            "chess-queen.png", "chess-rook.png", "chest-armor.png", "chest.png",
            "chestnut-leaf.png", "chewed-heart.png", "chewed-skull.png", "chicken-leg.png",
            "chicken-oven.png", "chicken.png", "chili-pepper.png", "chimney.png",
            "chips-bag.png", "chisel.png", "chocolate-bar.png", "choice.png",
            "chopped-skull.png", "chopsticks.png", "church.png", "cigale.png", "cigar.png",
            "cigarette.png", "circle-cage.png", "circle-claws.png", "circle-forest.png",
            "circle-sparks.png", "circle.png", "circling-fish.png", "circuitry.png",
            "circular-saw.png", "circular-sawblade.png", "city-car.png", "clamp.png",
            "clapperboard.png", "clarinet.png", "classical-knowledge.png",
            "claw-hammer.png", "claw-slashes.png", "claw-string.png", "claw.png",
            "claws.png", "clay-brick.png", "claymore-explosive.png", "cleaver.png",
            "cleopatra.png", "click.png", "cliff-crossing.png", "cloak-dagger.png",
            "cloak.png", "cloaked-figure-on-horseback.png", "clock-tower.png",
            "clockwise-rotation.png", "clockwork.png", "closed-barbute.png",
            "closed-doors.png", "cloth-jar.png", "clothes.png", "clothesline.png",
            "clothespin.png", "cloud-download.png", "cloud-ring.png", "cloud-upload.png",
            "cloudy-fork.png", "clout.png", "clover-alt.png", "clover-spiked.png",
            "clover.png", "clown.png", "clownfish.png", "clubs.png", "cluster-bomb.png",
            "coa-de-jima.png", "coal-pile.png", "coal-wagon.png", "cobra-alt.png",
            "cobra.png", "cobweb.png", "coconuts.png", "coffee-beans.png", "coffee-cup.png",
            "coffee-mug.png", "coffee-pot.png", "coffin.png", "cog-lock.png", "cog.png",
            "cogsplosion.png", "coiled-nail.png", "coiling-curl.png", "coinflip.png",
            "coins-pile.png", "coins.png", "cold-heart.png", "coliseum.png", "colombia.png",
            "colombian-statue.png", "colt-m1911.png", "column-vase.png", "coma.png",
            "comb.png", "combination-lock.png", "comet-spark.png",
            "commercial-airplane.png", "compact-disc.png", "companion-cube.png",
            "compass.png", "computer-fan.png", "computing.png", "concentration-orb.png",
            "concentric-crescents.png", "concrete-bag.png", "condor-emblem.png",
            "condylura-skull.png", "confirmed.png", "confrontation.png", "congress.png",
            "conqueror.png", "console-controller.png", "contortionist.png", "contract.png",
            "control-tower.png", "convergence-target.png", "conversation.png",
            "converse-shoe.png", "convict.png", "convince.png", "conway-life-glider.png",
            "cook.png", "cookie.png", "cooking-glove.png", "cooking-pot.png",
            "cool-spices.png", "cooler.png", "cootie-catcher.png", "coral.png",
            "cork-hat.png", "corked-tube.png", "corkscrew.png", "corn.png",
            "corner-explosion.png", "corner-flag.png", "cornucopia.png", "coronation.png",
            "corporal.png", "corset.png", "corsica.png", "cosmic-egg.png",
            "cotton-flower.png", "covered-jar.png", "cow.png", "cowboy-boot.png",
            "cowboy-holster.png", "cowled.png", "cpu-shot.png", "cpu.png", "crab-claw.png",
            "crab.png", "cracked-alien-skull.png", "cracked-ball-dunk.png",
            "cracked-disc.png", "cracked-glass.png", "cracked-helm.png", "cracked-mask.png",
            "cracked-saber.png", "cracked-shield.png", "crafting.png", "crags.png",
            "crane.png", "credits-currency.png", "crenel-crown.png",
            "crenulated-shield.png", "crescent-blade-alt.png", "crescent-blade.png",
            "crescent-staff.png", "crested-helmet.png", "cricket-bat.png", "cricket.png",
            "crime-scene-tape.png", "croc-jaws.png", "croc-sword.png", "croissant.png",
            "croissants-pupil.png", "crook-flail.png", "cross-flare.png", "cross-mark.png",
            "cross-shield.png", "crossbow.png", "crosscut-saw.png", "crossed-air-flows.png",
            "crossed-axes.png", "crossed-bones.png", "crossed-chains.png",
            "crossed-claws.png", "crossed-pistols.png", "crossed-sabres.png",
            "crossed-slashes.png", "crossed-swords.png", "crosshair-arrow.png",
            "crosshair.png", "crossroad.png", "crow-dive.png", "crow-nest.png",
            "crowbar.png", "crown-coin.png", "crown-of-thorns.png", "crown.png",
            "crowned-explosion.png", "crowned-heart.png", "crowned-skull.png",
            "crucifix.png", "cruiser.png", "crumbling-ball.png", "crush.png",
            "cryo-chamber.png", "crypt-entrance.png", "crystal-ball.png",
            "crystal-bars.png", "crystal-cluster.png", "crystal-earrings.png",
            "crystal-eye.png", "crystal-growth.png", "crystal-shine.png",
            "crystal-shrine.png", "crystal-wand.png", "crystalize.png", "cuauhtli.png",
            "cube.png", "cubeforce.png", "cubes.png", "cuckoo-clock.png", "cultist-alt.png",
            "cultist.png", "cupcake.png", "cupidon-arrow.png", "curled-leaf.png",
            "curled-tentacle.png", "curling-stone.png", "curling-vines.png",
            "curly-mask.png", "curly-wing.png", "cursed-star.png", "curvy-knife.png",
            "custodian-helmet.png", "cut-diamond.png", "cut-lemon.png", "cut-palm.png",
            "cyber-eye.png", "cyborg-face.png", "cycle.png", "cycling.png", "cyclops.png",
            "cz-skorpion.png", "d10.png", "d12.png", "d4.png", "daemon-pull.png",
            "daemon-skull.png", "dagger-rose.png", "daggers.png", "daisy.png", "dam.png",
            "damaged-house.png", "dandelion-flower.png", "dango.png", "dark-squad.png",
            "dart.png", "database.png", "dead-eye.png", "dead-head.png", "dead-wood.png",
            "deadly-strike.png", "death-juice.png", "death-note.png", "death-skull.png",
            "death-star.png", "death-zone.png", "deathcab.png", "decapitation.png",
            "deer-head.png", "deer-track.png", "deer.png", "defense-satellite.png",
            "defensive-wall.png", "defibrilate.png", "deku-tree.png",
            "delicate-perfume.png", "delighted.png", "delivery-drone.png", "demolish.png",
            "dervish-swords.png", "desert-camp.png", "desert-eagle.png", "desert-skull.png",
            "desert.png", "deshret-red-crown.png", "desk-lamp.png", "desk.png",
            "despair.png", "detonator.png", "detour.png", "devil-mask.png", "dew.png",
            "diablo-skull.png", "diagram.png", "dial-padlock.png", "diamond-hard.png",
            "diamond-hilt.png", "diamond-ring.png", "diamond-trophy.png",
            "diamonds-smile.png", "diamonds.png", "dice-eight-faces-eight.png",
            "dice-fire.png", "dice-shield.png", "dice-six-faces-five.png",
            "dice-six-faces-four.png", "dice-six-faces-one.png", "dice-six-faces-six.png",
            "dice-six-faces-three.png", "dice-six-faces-two.png", "dice-target.png",
            "dice-twenty-faces-one.png", "dice-twenty-faces-twenty.png", "dig-dug.png",
            "dig-hole.png", "digital-trace.png", "dimetrodon.png", "dinosaur-bones.png",
            "dinosaur-egg.png", "dinosaur-rex.png", "diplodocus.png", "diploma.png",
            "direction-sign.png", "direction-signs.png", "director-chair.png",
            "direwolf.png", "disc-golf-bag.png", "disc-golf-basket.png", "disc.png",
            "discobolus.png", "discussion.png", "disintegrate.png", "distraction-alt.png",
            "distraction.png", "distress-signal.png", "divergence.png", "divert.png",
            "divided-spiral.png", "divided-square.png", "diving-dagger.png",
            "diving-helmet.png", "djed-pillar.png", "djembe.png", "djinn.png", "dna1.png",
            "dna2.png", "doctor-face.png", "dodge.png", "dodging.png", "dodo.png",
            "dog-bowl.png", "dog-house.png", "dolmen.png", "dolphin.png", "domino-mask.png",
            "domino-tiles.png", "doner-kebab.png", "donkey.png", "donut.png",
            "door-handle.png", "door-ring-handle.png", "door-watcher.png", "door.png",
            "doorway.png", "dorsal-scales.png", "double-diaphragm.png", "double-dragon.png",
            "double-face-mask.png", "double-fish.png", "double-necklace.png",
            "double-quaver.png", "double-ringed-orb.png", "double-shot.png",
            "double-street-lights.png", "doubled.png", "dough-roller.png", "dove.png",
            "dozen.png", "dragon-balls.png", "dragon-breath.png", "dragon-head-alt.png",
            "dragon-head.png", "dragon-orb.png", "dragon-shield.png", "dragon-spiral.png",
            "dragonfly.png", "drakkar-dragon.png", "drakkar.png", "drama-masks.png",
            "drawbridge.png", "dread-skull.png", "dread.png", "dreadnought.png",
            "dream-catcher.png", "dress.png", "drill-alt.png", "drill.png", "drink-me.png",
            "drinking.png", "dripping-blade.png", "dripping-goo.png", "dripping-honey.png",
            "dripping-knife.png", "dripping-star.png", "dripping-stone.png",
            "dripping-sword.png", "dripping-tube.png", "drop-earrings.png",
            "drop-weapon.png", "drop.png", "droplet-splash.png", "droplets.png",
            "drowning.png", "drum-kit.png", "drum.png", "duality-mask.png", "duality.png",
            "duck-palm.png", "duck.png", "duel.png", "duffel-bag.png", "dumpling-bao.png",
            "dumpling.png", "dunce-cap.png", "dungeon-gate.png", "dungeon-light.png",
            "duration.png", "dust-cloud.png", "dutch-bike.png", "dwarf-face.png",
            "dwarf-helmet.png", "dwarf-king.png", "dwennimmen.png", "dynamite.png",
            "eagle-emblem.png", "eagle-head.png", "earbuds.png", "earrings.png",
            "earth-africa-europe.png", "earth-america.png", "earth-asia-oceania.png",
            "earth-crack.png", "earth-spit.png", "earth-worm.png", "earwig.png",
            "easel.png", "easter-egg.png", "eating-pelican.png", "eating.png",
            "echo-ripples.png", "eclipse-flare.png", "eclipse-saw.png", "eclipse.png",
            "ecology.png", "edge-crack.png", "edged-shield.png", "eel.png",
            "egg-clutch.png", "egg-defense.png", "egg-eye.png", "egg-pod.png", "egypt.png",
            "egyptian-bird.png", "egyptian-profile.png", "egyptian-pyramids.png",
            "egyptian-sphinx.png", "egyptian-temple.png", "egyptian-urns.png",
            "egyptian-walk.png", "eight-ball.png", "elbow-pad.png", "elderberry.png",
            "electric-whip.png", "electric.png", "electrical-crescent.png",
            "electrical-resistance.png", "electrical-socket.png", "elephant-head.png",
            "elephant.png", "elevator.png", "elf-ear.png", "elf-helmet.png",
            "elven-castle.png", "elysium-shade.png", "ember-shot.png",
            "embrassed-energy.png", "embryo.png", "emerald-necklace.png", "emerald.png",
            "empty-chessboard.png", "empty-hourglass.png", "empty-metal-bucket-handle.png",
            "empty-metal-bucket.png", "empty-wood-bucket-handle.png",
            "empty-wood-bucket.png", "encirclement.png", "encrypted-channel.png",
            "energise.png", "energy-arrow.png", "energy-breath.png", "energy-shield.png",
            "energy-sword.png", "energy-tank.png", "engagement-ring.png",
            "enlightenment.png", "enrage.png", "ent-mouth.png", "entangled-typhoon.png",
            "entry-door.png", "envelope.png", "erlenmeyer.png", "ermine.png",
            "eruption.png", "escalator.png", "eternal-love.png", "european-flag.png",
            "evasion.png", "evil-bat.png", "evil-book.png", "evil-bud.png",
            "evil-comet.png", "evil-eyes.png", "evil-fork.png", "evil-hand.png",
            "evil-love.png", "evil-minion.png", "evil-moon.png", "evil-tower.png",
            "evil-tree.png", "evil-wings.png", "executioner-hood.png", "exit-door.png",
            "expand.png", "expanded-rays.png", "expander.png", "expense.png",
            "exploding-planet.png", "explosion-rays.png", "explosive-materials.png",
            "explosive-meeting.png", "extra-lucid.png", "extra-time.png",
            "extra-vision.png", "extraction-orb.png", "eye-of-horus.png", "eye-shield.png",
            "eye-target.png", "eyeball.png", "eyedropper.png", "eyelashes.png",
            "eyepatch.png", "eyestalk.png", "f-clef.png", "f1-car.png", "face-to-face.png",
            "factory-arm.png", "factory.png", "fairy-alt.png", "fairy-wand.png",
            "fairy-wings.png", "fairy.png", "falcon-moon.png", "fall-down.png",
            "falling-blob.png", "falling-bomb.png", "falling-boulder.png",
            "falling-eye.png", "falling-leaf.png", "falling-ovoid.png", "falling-rocks.png",
            "falling-star.png", "falling.png", "fallout-shelter.png", "famas.png",
            "family-house.png", "family-tree.png", "fanged-skull.png", "fangs-circle.png",
            "fangs.png", "farm-tractor.png", "farmer.png", "fast-arrow.png",
            "fast-backward-button.png", "fast-forward-button.png", "fast-noodles.png",
            "fat.png", "feather-necklace.png", "feather-wound.png", "feather.png",
            "feathered-wing.png", "fedora.png", "feline.png", "female-legs.png",
            "female-vampire.png", "female.png", "fencer.png", "fern.png",
            "fertilizer-bag.png", "fetus.png", "fez.png", "field-gun.png", "field.png",
            "figurehead.png", "files.png", "film-projector.png", "film-spool.png",
            "film-strip.png", "finch.png", "finger-print.png", "fingernail.png",
            "fingers-crossed.png", "finish-line.png", "fire-ace.png", "fire-axe.png",
            "fire-bomb.png", "fire-bottle.png", "fire-bowl.png", "fire-breath.png",
            "fire-dash.png", "fire-extinguisher.png", "fire-flower.png", "fire-gem.png",
            "fire-iris.png", "fire-punch.png", "fire-ray.png", "fire-ring.png",
            "fire-shield.png", "fire-shrine.png", "fire-silhouette.png",
            "fire-spell-cast.png", "fire-tail.png", "fire-wave.png", "fire-zone.png",
            "fire.png", "fireball.png", "fireflake.png", "fireplace.png", "firewall.png",
            "firework-rocket.png", "first-aid-kit.png", "fish-bucket.png",
            "fish-cooked.png", "fish-corpse.png", "fish-eggs.png", "fish-escape.png",
            "fish-monster.png", "fish-scales.png", "fish-smoking.png", "fishbone.png",
            "fishhook-fork.png", "fishing-boat.png", "fishing-hook.png", "fishing-jig.png",
            "fishing-lure.png", "fishing-net.png", "fishing-pole.png", "fishing-spoon.png",
            "fishing.png", "fission.png", "fist-alt.png", "fist.png", "fizzing-flask.png",
            "flag-objective.png", "flail.png", "flake.png", "flame-claws.png",
            "flame-spin.png", "flame-tunnel.png", "flame.png", "flamed-leaf.png",
            "flamer.png", "flamethrower-soldier.png", "flamethrower.png",
            "flaming-arrow.png", "flaming-claw.png", "flaming-sheet.png",
            "flaming-trident.png", "flamingo.png", "flanged-mace.png", "flash-grenade.png",
            "flashlight.png", "flat-hammer.png", "flat-paw-print.png", "flat-platform.png",
            "flat-star.png", "flat-tire.png", "flatbed-covered.png", "flatbed.png",
            "flatfish.png", "flax.png", "fleshy-mass.png", "fleur-de-lys.png",
            "flexible-lamp.png", "flexible-star.png", "flint-spark.png", "flip-flops.png",
            "floating-crystal.png", "floating-ghost.png", "floating-platforms.png",
            "floating-tentacles.png", "flood.png", "floor-hatch.png", "floor-polisher.png",
            "flour.png", "flower-emblem.png", "flower-hat.png", "flower-pot.png",
            "flower-star.png", "flower-twirl.png", "flowers.png", "fluffy-cloud.png",
            "fluffy-flame.png", "fluffy-swirl.png", "fluffy-trefoil.png", "fluffy-wing.png",
            "flute.png", "fly.png", "flying-beetle.png", "flying-dagger.png",
            "flying-flag.png", "flying-fox.png", "flying-shuriken.png", "flying-target.png",
            "flying-trout.png", "fn-fal.png", "foam.png", "foamy-disc.png",
            "focused-lightning.png", "fog-light.png", "fog.png", "folded-paper.png",
            "fomorian.png", "food-chain.png", "food-truck.png", "foot-plaster.png",
            "foot-trip.png", "footprint.png", "footsteps.png", "footy-field.png",
            "forearm.png", "forest-camp.png", "forest-entrance.png", "forest.png",
            "fork-knife-spoon.png", "forklift.png", "forward-field.png", "forward-sun.png",
            "fossil.png", "foundry-bucket.png", "fountain-pen.png", "fountain.png",
            "fox-head.png", "fox-tail.png", "fox.png", "fragmented-meteor.png",
            "fragmented-sword.png", "fragrance.png", "france.png",
            "frankenstein-creature.png", "frayed-arrow.png", "freedom-dove.png",
            "freemasonry.png", "french-fries.png", "french-horn.png", "fridge.png",
            "fried-eggs.png", "fried-fish.png", "frisbee.png", "froe-and-mallet.png",
            "frog-foot.png", "frog-mouth-helm.png", "frog-prince.png", "frog.png",
            "front-teeth.png", "frontal-lobe.png", "frostfire.png", "frozen-arrow.png",
            "frozen-block.png", "frozen-body.png", "frozen-orb.png", "frozen-ring.png",
            "fruit-bowl.png", "fruit-tree.png", "fruiting.png", "fuel-tank.png", "fuji.png",
            "fulguro-punch.png", "full-folder.png", "full-metal-bucket-handle.png",
            "full-metal-bucket.png", "full-motorcycle-helmet.png", "full-pizza.png",
            "full-wood-bucket-handle.png", "full-wood-bucket.png", "funnel.png",
            "fur-boot.png", "fur-shirt.png", "furnace.png", "g-clef.png", "galaxy.png",
            "galea.png", "galleon.png", "galley.png", "game-console.png",
            "gamepad-cross.png", "gamepad.png", "gardening-shears.png", "gargoyle.png",
            "garlic.png", "gas-mask-alt.png", "gas-mask.png", "gas-pump.png",
            "gas-stove.png", "gate.png", "gauls-helm.png", "gauntlet.png", "gavel.png",
            "gaze.png", "gear-hammer.png", "gear-stick-pattern.png", "gear-stick.png",
            "gears.png", "gecko.png", "gem-chain.png", "gem-necklace.png",
            "gem-pendant.png", "gemini.png", "gems.png", "ghost-ally.png", "ghost.png",
            "giant-squid.png", "giant.png", "gibbet.png", "gift-of-knowledge.png",
            "gift-trap.png", "gingerbread-man.png", "ginkgo-leaf.png", "gladius.png",
            "glaive.png", "glass-ball.png", "glass-celebration.png", "glass-heart.png",
            "glass-shot.png", "glider.png", "globe-ring.png", "globe.png", "glock.png",
            "gloop.png", "gloves.png", "glowing-artifact.png", "glowing-hands.png",
            "gluttonous-smile.png", "gluttony.png", "goal-keeper.png", "goat.png",
            "goblin-camp.png", "goblin-head.png", "goblin.png", "gold-bar.png",
            "gold-mine.png", "gold-nuggets.png", "gold-scarab.png", "gold-shell.png",
            "gold-stack.png", "golem-head.png", "golf-flag.png", "golf-tee.png", "gong.png",
            "goo-explosion.png", "goo-skull.png", "goo-spurt.png", "gooey-daemon.png",
            "gooey-eyed-sun.png", "gooey-impact.png", "gooey-molecule.png",
            "gooey-sword.png", "goose.png", "gorilla.png", "gothic-cross.png", "gps.png",
            "grab.png", "graduate-cap.png", "grain-bundle.png", "grain.png", "granary.png",
            "grand-piano.png", "grapes.png", "grapple.png", "grasping-claws.png",
            "grasping-slug.png", "grass-mushroom.png", "grass.png", "grave-flowers.png",
            "graveyard.png", "gravitation.png", "grease-trap.png", "great-pyramid.png",
            "great-war-tank.png", "greaves.png", "greek-sphinx.png", "greek-temple.png",
            "green-power.png", "greenhouse.png", "grenade-alt.png", "grenade.png",
            "griffin-shield.png", "griffin-symbol.png", "grim-reaper.png",
            "ground-sprout.png", "groundbreaker.png", "grouped-drops.png", "growth.png",
            "guarded-tower.png", "guards.png", "guatemala.png", "guillotine.png",
            "guitar-bass-head.png", "guitar-head.png", "guitar.png", "gun-rose.png",
            "gun-stock.png", "gunshot.png", "gym-bag.png", "gyroscope.png", "h2o.png",
            "habitat-dome.png", "hades-symbol.png", "hair-strands.png",
            "halberd-shuriken.png", "halberd.png", "half-body-crawling.png",
            "half-dead.png", "half-heart.png", "half-log.png", "half-tornado.png",
            "halt.png", "ham-shank.png", "hamburger-menu.png", "hamburger.png",
            "hammer-break.png", "hammer-drop.png", "hammer-nails.png", "hammer-sickle.png",
            "hand-alt.png", "hand-bag.png", "hand-bandage.png", "hand-grip.png",
            "hand-of-god.png", "hand-ok.png", "hand-saw.png", "hand-truck.png",
            "hand-wing.png", "hand.png", "handcuffed.png", "handcuffs.png",
            "handheld-fan.png", "hang-glider-alt.png", "hang-glider.png", "hanger.png",
            "hanging-sign.png", "hanging-spider.png", "happy-skull.png", "harbor-dock.png",
            "harp.png", "harpoon-chain.png", "harpoon-trident.png", "harpy.png",
            "harry-potter-skull.png", "hasty-grave.png", "hatchet.png", "hatchets.png",
            "haunting.png", "hawk-emblem.png", "hazard-sign.png", "hazmat-suit.png",
            "head-shot.png", "headband-knot.png", "headphones.png", "headshot-alt.png",
            "headshot.png", "healing-shield.png", "healing.png", "health-capsule.png",
            "health-decrease.png", "health-increase.png", "health-normal.png",
            "health-potion.png", "hearing-disabled.png", "heart-armor.png",
            "heart-battery.png", "heart-beats.png", "heart-bottle.png", "heart-drop.png",
            "heart-earrings.png", "heart-inside.png", "heart-key.png", "heart-minus.png",
            "heart-necklace.png", "heart-organ.png", "heart-plus.png", "heart-shield.png",
            "heart-stake.png", "heart-tower.png", "heart-wings.png", "heartburn.png",
            "hearts.png", "heat-haze.png", "heaven-gate.png", "heavy-arrow.png",
            "heavy-bullets.png", "heavy-collar.png", "heavy-fall.png", "heavy-fighter.png",
            "heavy-helm.png", "heavy-lightning.png", "heavy-rain.png",
            "heavy-thorny-triskelion.png", "heavy-timer.png", "hedgehog.png",
            "hedjet-white-crown.png", "helicoprion.png", "helicopter-tail.png",
            "helicopter.png", "hell-crosses.png", "helmet-head-shot.png", "helmet.png",
            "help.png", "hemp.png", "heptagram.png", "heraldic-sun.png", "herbs-bundle.png",
            "heron.png", "hexagonal-nut.png", "hexes.png", "hidden.png",
            "hieroglyph-legs.png", "hieroglyph-y.png", "high-five.png", "high-grass.png",
            "high-heel.png", "high-kick.png", "high-punch.png", "high-shot.png",
            "high-tide.png", "highlighter.png", "hiking.png", "hill-conquest.png",
            "hill-fort.png", "hills.png", "histogram.png", "hive-mind.png", "hive.png",
            "hobbit-door.png", "hobbit-dwelling.png", "hockey.png", "hole-ladder.png",
            "hole.png", "hollow-cat.png", "holosphere.png", "holy-grail.png",
            "holy-hand-grenade.png", "holy-oak.png", "holy-symbol.png", "holy-water.png",
            "home-garage.png", "honey-jar.png", "honeycomb.png", "honeypot.png", "hood.png",
            "hooded-assassin.png", "hooded-figure.png", "hoodie.png", "hoof.png",
            "hook-swords.png", "hook.png", "hops.png", "horizon-road.png",
            "horizontal-flip.png", "horn-internal.png", "horned-helm.png",
            "horned-reptile.png", "horned-skull.png", "horse-head-alt.png",
            "horse-head.png", "horseshoe.png", "horus.png", "hospital-cross.png",
            "hospital.png", "hot-dog.png", "hot-meal.png", "hot-spices.png",
            "hot-surface.png", "hound.png", "hourglass.png", "house-keys.png", "house.png",
            "human-cannonball.png", "human-ear.png", "human-pyramid.png",
            "human-target.png", "hummingbird.png", "hungary.png", "hunter-eyes.png",
            "hunting-bolas.png", "hunting-horn.png", "hut.png", "huts-village.png",
            "hydra-shot.png", "hydra.png", "hyena-head.png", "hypersonic-bolt.png",
            "hypersonic-melon.png", "hypodermic-test.png", "i-beam.png", "i-brick.png",
            "ibis.png", "icarus.png", "ice-bolt.png", "ice-bomb.png", "ice-cream-cone.png",
            "ice-cream-scoop.png", "ice-cube.png", "ice-cubes.png", "ice-golem.png",
            "ice-iris.png", "ice-pop.png", "ice-shield.png", "ice-skate.png",
            "ice-spear.png", "ice-spell-cast.png", "iceberg.png", "icebergs.png",
            "iceland.png", "icicles-aura.png", "icicles-fence.png", "id-card.png",
            "idea.png", "ifrit.png", "igloo.png", "imbricated-arrows.png", "imp-laugh.png",
            "imp.png", "impact-point.png", "imperial-crown.png", "implosion.png",
            "imprisoned.png", "inauguration.png", "incense.png", "incisors.png",
            "incoming-rocket.png", "incubator.png", "india-gate.png", "indian-palace.png",
            "inferno-bomb.png", "infested-mass.png", "infinity.png", "info.png",
            "injustice.png", "ink-swirl.png", "inner-self.png", "insect-jaws.png",
            "inspiration.png", "interceptor-ship.png", "interdiction.png",
            "interlaced-tentacles.png", "interleaved-arrows.png", "interleaved-claws.png",
            "internal-injury.png", "internal-organ.png", "interstellar-path.png",
            "intricate-necklace.png", "inverted-dice-1.png", "inverted-dice-2.png",
            "inverted-dice-3.png", "inverted-dice-4.png", "inverted-dice-5.png",
            "inverted-dice-6.png", "invisible-face.png", "invisible.png",
            "ion-cannon-blast.png", "ionic-column.png", "iraq.png", "iron-cross.png",
            "iron-hulled-warship.png", "iron-mask.png", "island.png", "italia.png",
            "ivory-tusks.png", "j-brick.png", "jack-plug.png", "james-bond-aperture.png",
            "japan.png", "japanese-bridge.png", "jasmine.png", "jason-mask.png",
            "jawbone.png", "jawless-cyclop.png", "jeep-alt.png", "jeep.png",
            "jelly-beans.png", "jelly.png", "jellyfish.png", "jerrycan.png",
            "jerusalem-cross.png", "jester-hat.png", "jet-fighter.png", "jet-pack.png",
            "jetpack.png", "jewel-crown.png", "jeweled-chalice.png", "jigsaw-box.png",
            "jigsaw-piece.png", "join.png", "joint.png", "journey.png", "joystick.png",
            "jug.png", "juggler.png", "juggling-clubs.png", "juggling-seal.png",
            "jump-across.png", "jumping-dog.png", "jumping-rope.png", "jungle.png",
            "jupiter.png", "justice-star.png", "kaleidoscope-pearls.png", "kangaroo.png",
            "katana.png", "kebab-spit.png", "kenku-head.png", "kenya.png", "ketchup.png",
            "kevlar-vest.png", "kevlar.png", "key-alt.png", "key-card.png", "key-lock.png",
            "key.png", "keyboard.png", "keyring.png", "kick-scooter.png", "kid-slide.png",
            "kidneys.png", "kimono.png", "kindle.png", "king-ju-mask.png", "king.png",
            "kitchen-knives.png", "kitchen-scale.png", "kitchen-tap.png", "kite.png",
            "kiwi-bird.png", "kiwi-fruit.png", "klingon.png", "knapsack.png",
            "knee-bandage.png", "knee-cap.png", "knee-pad.png", "kneeling.png",
            "knife-fork.png", "knife-thrust.png", "knight-banner.png",
            "knocked-out-stars.png", "knockout.png", "knot.png", "koala.png",
            "koholint-egg.png", "kraken-tentacle.png", "kusarigama.png", "l-brick.png",
            "lab-coat.png", "labrador-head.png", "ladder.png", "ladders-platform.png",
            "ladle.png", "ladybug.png", "lambda.png", "lamellar.png", "lamprey-mouth.png",
            "land-mine.png", "lantern-flame.png", "lantern.png", "laptop.png",
            "large-dress.png", "large-paint-brush.png", "large-wound.png",
            "laser-blast.png", "laser-burst.png", "laser-gun.png", "laser-precision.png",
            "laser-sparks.png", "laser-turret.png", "laser-warning.png", "laserburn.png",
            "lasso.png", "latvia.png", "laurel-crown.png", "laurels-trophy.png",
            "laurels.png", "lava.png", "law-star.png", "layered-armor.png", "lead-pipe.png",
            "leaf-skeleton.png", "leaf-swirl.png", "leak.png", "leaky-skull.png",
            "leapfrog.png", "leather-armor.png", "leather-boot.png", "leather-vest.png",
            "led.png", "lee-enfield.png", "leeching-worm.png", "leek.png", "leg-armor.png",
            "leg.png", "lemon.png", "leo.png", "letter-bomb.png", "level-crossing.png",
            "level-end-flag.png", "level-four-advanced.png", "level-four.png",
            "level-three-advanced.png", "level-three.png", "level-two-advanced.png",
            "level-two.png", "lever.png", "liar.png", "liberty-wing.png", "libra.png",
            "libya.png", "life-bar.png", "life-buoy.png", "life-in-the-balance.png",
            "life-jacket.png", "life-support.png", "life-tap.png", "lift.png",
            "light-backpack.png", "light-bulb.png", "light-fighter.png", "light-helm.png",
            "light-projector.png", "light-sabers.png", "light-thorny-triskelion.png",
            "lighter.png", "lighthouse.png", "lightning-arc.png", "lightning-bow.png",
            "lightning-branches.png", "lightning-dissipation.png", "lightning-dome.png",
            "lightning-electron.png", "lightning-flame.png", "lightning-frequency.png",
            "lightning-helix.png", "lightning-mask.png", "lightning-saber.png",
            "lightning-shadow.png", "lightning-shield.png", "lightning-shout.png",
            "lightning-slashes.png", "lightning-spanner.png", "lightning-storm.png",
            "lightning-tear.png", "lightning-tree.png", "lightning-trio.png",
            "lily-pads.png", "linden-leaf.png", "linked-rings.png", "lion.png", "lips.png",
            "lipstick.png", "liquid-soap.png", "lit-candelabra.png", "liver.png",
            "lizard-tongue.png", "lizardman.png", "load.png", "lob-arrow.png",
            "lock-picking.png", "lock-spy.png", "locked-box.png", "locked-chest.png",
            "locked-door.png", "locked-fortress.png", "locked-heart.png", "lockers.png",
            "lockpicks.png", "log.png", "logging.png", "logic-gate-and.png",
            "logic-gate-nand.png", "logic-gate-nor.png", "logic-gate-not.png",
            "logic-gate-nxor.png", "logic-gate-or.png", "logic-gate-xor.png",
            "loincloth.png", "long-antennae-bug.png", "long-legged-spider.png",
            "look-at.png", "lorgnette.png", "lost-limb.png", "lotus-flower.png",
            "lotus.png", "louvre-pyramid.png", "love-howl.png", "love-injection.png",
            "love-letter.png", "love-mystery.png", "love-song.png", "lovers.png",
            "low-tide.png", "luchador.png", "lucifer-cannon.png", "lucky-fisherman.png",
            "luger.png", "lunar-module.png", "lunar-wand.png", "lungs.png", "lynx-head.png",
            "lyre.png", "m3-grease-gun.png", "mac-10.png", "mace-head.png", "machete.png",
            "machine-gun-magazine.png", "machine-gun.png", "mad-scientist.png",
            "maggot.png", "magic-axe.png", "magic-broom.png", "magic-gate.png",
            "magic-hat.png", "magic-lamp.png", "magic-palm.png", "magic-portal.png",
            "magic-potion.png", "magic-shield.png", "magic-swirl.png", "magic-trident.png",
            "magick-trick.png", "magnet-blast.png", "magnet-man.png", "magnet.png",
            "magnifying-glass.png", "mail-shirt.png", "mailbox.png", "mailed-fist.png",
            "male.png", "mammoth.png", "manacles.png", "mandrill-head.png", "manta-ray.png",
            "mantrap.png", "manual-juicer.png", "manual-meat-grinder.png",
            "manual-water-pump.png", "maple-leaf.png", "maracas.png", "marble-tap.png",
            "marbles.png", "marrow-drain.png", "mars-curiosity.png", "mars-pathfinder.png",
            "marshmallows.png", "martini.png", "martyr-memorial.png", "masked-spider.png",
            "mason-jar.png", "mass-driver.png", "master-of-arms.png", "match-head.png",
            "match-tip.png", "matchbox.png", "materials-science.png",
            "matryoshka-dolls.png", "matter-states.png", "mayan-pyramid.png",
            "maze-cornea.png", "maze-saw.png", "maze.png", "meal.png", "measure-tape.png",
            "meat-cleaver.png", "meat-hook.png", "meat.png", "mecha-head.png",
            "mecha-mask.png", "mechanic-garage.png", "mechanical-arm.png",
            "medal-skull.png", "medal.png", "medallist.png", "medical-drip.png",
            "medical-pack-alt.png", "medical-pack.png", "medical-thermometer.png",
            "medicine-pills.png", "medicines.png", "medieval-barracks.png",
            "medieval-gate.png", "medieval-pavilion.png", "medieval-village-01.png",
            "meditation.png", "medusa-head.png", "meeple-army.png", "meeple-circle.png",
            "meeple-group.png", "meeple-king.png", "meeple.png", "megabot.png",
            "megaphone.png", "melting-ice-cube.png", "melting-metal.png", "menhir.png",
            "mermaid.png", "mesh-ball.png", "mesh-network.png", "metal-bar.png",
            "metal-boot.png", "metal-detector.png", "metal-disc.png",
            "metal-golem-head.png", "metal-hand.png", "metal-plate.png", "metal-scales.png",
            "metal-skirt.png", "meteor-impact.png", "metroid.png", "metronome.png",
            "mexico.png", "microchip.png", "microphone.png", "microscope-lens.png",
            "microscope.png", "mid-summit.png", "middle-arrow.png", "midnight-claw.png",
            "mighty-boosh.png", "mighty-force.png", "mighty-horn.png", "mighty-spanner.png",
            "military-ambulance.png", "military-fort.png", "milk-carton.png",
            "millenium-key.png", "mimic-chest.png", "mine-explosion.png", "mine-truck.png",
            "mine-wagon.png", "minefield.png", "miner.png", "mineral-heart.png",
            "mineral-pearls.png", "minerals.png", "mini-submarine.png", "minigun.png",
            "mining-helmet.png", "mining.png", "minions.png", "minotaur.png",
            "miracle-medecine.png", "mirror-mirror.png", "misdirection.png",
            "missile-launcher.png", "missile-mech.png", "missile-pod.png",
            "missile-swarm.png", "mite-alt.png", "mite.png", "moai.png", "modern-city.png",
            "moebius-star.png", "moebius-trefoil.png", "moebius-triangle.png",
            "moka-pot.png", "moldova.png", "mole.png", "molecule-alt.png", "molecule.png",
            "molotov.png", "mona-lisa.png", "moncler-jacket.png", "money-stack.png",
            "mongolia.png", "monk-face.png", "monkey-wrench.png", "monkey.png",
            "mono-wheel-robot.png", "monster-grasp.png", "monstera-leaf.png",
            "monument-valley.png", "moon-bats.png", "moon-claws.png", "moon-orbit.png",
            "moon.png", "mooring-bollard.png", "morbid-humour.png", "morgue-feet.png",
            "morph-ball.png", "mortar.png", "mountain-cave.png", "mountain-climbing.png",
            "mountain-road.png", "mountains.png", "mountaintop.png", "mounted-knight.png",
            "mouse-alt.png", "mouse.png", "mouth-watering.png", "move.png",
            "movement-sensor.png", "mp-40.png", "mp5-alt.png", "mp5.png", "mp5k.png",
            "mucous-pillar.png", "mug-shot.png", "multi-directions.png",
            "multiple-targets.png", "mummy-head.png", "muscle-fat.png", "muscle-up.png",
            "muscular-torso.png", "mushroom-cloud.png", "mushroom-gills.png",
            "mushroom-house.png", "mushroom.png", "mushrooms-cluster.png", "mushrooms.png",
            "music-spell.png", "musical-keyboard.png", "musical-notes.png",
            "musical-score.png", "musket.png", "mussel.png", "mustache.png", "mute.png",
            "nachos.png", "nailed-foot.png", "nailed-head.png", "nails.png", "nano-bot.png",
            "nautilus-shell.png", "neck-bite.png", "necklace-display.png", "necklace.png",
            "nectar.png", "needle-drill.png", "needle-jaws.png", "nefertiti.png",
            "nest-birds.png", "nest-eggs.png", "nested-eclipses.png", "nested-hearts.png",
            "nested-hexagons.png", "network-bars.png", "new-born.png", "new-shoot.png",
            "newspaper.png", "next-button.png", "nigeria.png", "night-sky.png",
            "night-sleep.png", "night-vision.png", "ninja-armor.png", "ninja-head.png",
            "ninja-heroic-stance.png", "ninja-mask.png", "ninja-star.png",
            "ninja-velociraptor.png", "nodular.png", "noodle-ball.png", "noodles.png",
            "north-star-shuriken.png", "nose-front.png", "nose-side.png", "notebook.png",
            "nothing-to-say.png", "nuclear-bomb.png", "nuclear-plant.png",
            "nuclear-waste.png", "nuclear.png", "nun-face.png", "nunchaku.png",
            "nurse-female.png", "nurse-male.png", "o-brick.png", "oak-leaf.png", "oak.png",
            "oasis.png", "oat.png", "obelisk.png", "observatory.png", "ocarina.png",
            "occupy.png", "octogonal-eye.png", "octoman.png", "octopus.png", "oden.png",
            "office-chair.png", "offshore-platform.png", "ogre.png", "oil-can.png",
            "oil-drum.png", "oil-pump.png", "oil-rig.png", "oily-spiral.png",
            "old-king.png", "old-lantern.png", "old-microphone.png", "old-wagon.png",
            "olive.png", "omega.png", "on-sight.png", "on-target.png", "one-eyed.png",
            "oni.png", "onigori.png", "open-book.png", "open-chest.png", "open-folder.png",
            "open-gate.png", "open-palm.png", "open-treasure-chest.png", "open-wound.png",
            "opened-food-can.png", "opening-shell.png", "ophanim.png", "ophiuchus.png",
            "oppidum.png", "opposite-hearts.png", "oppression.png", "orange-slice.png",
            "orange.png", "orb-direction.png", "orb-wand.png", "orbit.png",
            "orbital-rays.png", "orbital.png", "orc-head.png", "ore.png", "organigram.png",
            "orrery.png", "ostrich.png", "otamatone.png", "ouroboros.png",
            "outback-hat.png", "over-infinity.png", "overdose.png", "overdrive.png",
            "overhead.png", "overkill.png", "overlord-helm.png", "overmind.png", "owl.png",
            "oyster-pearl.png", "oyster.png", "p90.png", "packed-planks.png",
            "paddle-steamer.png", "paddles.png", "padlock-open.png", "padlock.png",
            "pagoda.png", "paint-brush.png", "paint-bucket.png", "paint-roller.png",
            "painted-pottery.png", "palette.png", "palisade.png", "palm-tree.png",
            "palm.png", "pan-flute.png", "panda.png", "pangolin.png", "panzerfaust.png",
            "paper-arrow.png", "paper-bag-crumpled.png", "paper-bag-folded.png",
            "paper-bag-open.png", "paper-boat.png", "paper-bomb.png", "paper-clip.png",
            "paper-crane.png", "paper-frog.png", "paper-lantern.png", "paper-plane.png",
            "paper-tray.png", "paper-windmill.png", "paper.png", "papers.png",
            "papyrus.png", "parachute.png", "paraguay.png", "paranoia.png",
            "parasaurolophus.png", "park-bench.png", "parmecia.png", "parrot-head.png",
            "party-flags.png", "party-hat.png", "party-popper.png", "passport.png",
            "path-distance.png", "path-tile.png", "pauldrons.png", "pause-button.png",
            "paw-front.png", "paw-heart.png", "paw-print.png", "paw.png", "pawn.png",
            "pay-money.png", "pc.png", "peace-dove.png", "peach.png", "peaks.png",
            "peanut.png", "pear.png", "pearl-earring.png", "pearl-necklace.png", "peas.png",
            "pegasus.png", "pelvis-bone.png", "pencil-brush.png", "pencil-ruler.png",
            "pencil.png", "pendant-key.png", "pendulum-swing.png", "penguin.png",
            "pentacle.png", "pentagram-rose.png", "pentarrows-tornado.png",
            "perfume-bottle.png", "periscope.png", "perpendicular-rings.png",
            "person-in-bed.png", "person-in-blizzard.png", "person.png",
            "perspective-dice-five.png", "perspective-dice-four.png",
            "perspective-dice-one.png", "perspective-dice-six-faces-five.png",
            "perspective-dice-six-faces-four.png", "perspective-dice-six-faces-one.png",
            "perspective-dice-six-faces-random.png", "perspective-dice-six-faces-six.png",
            "perspective-dice-six-faces-three.png", "perspective-dice-six-faces-two.png",
            "perspective-dice-six.png", "perspective-dice-three.png",
            "perspective-dice-two.png", "peru.png", "pestle-mortar.png", "pharoah.png",
            "philosopher-bust.png", "phone.png", "photo-camera.png", "phrygian-cap.png",
            "pianist.png", "piano-keys.png", "pick-of-destiny.png", "pickelhaube.png",
            "pickle.png", "pie-chart.png", "pie-slice.png", "piece-skull.png",
            "pierced-body.png", "pierced-heart.png", "piercing-sword.png", "pig-face.png",
            "pig.png", "piggy-bank.png", "pikeman.png", "pilgrim-hat.png", "pill-drop.png",
            "pill.png", "pillow.png", "pimiento.png", "pin.png", "pinata.png",
            "pinball-flipper.png", "pincers.png", "pine-tree.png", "pineapple.png",
            "ping-pong-bat.png", "pipe-organ.png", "pipes.png", "piranha.png",
            "pirate-cannon.png", "pirate-captain.png", "pirate-coat.png", "pirate-flag.png",
            "pirate-grave.png", "pirate-hat.png", "pirate-hook.png", "pirate-skull.png",
            "pisa-tower.png", "pisces.png", "pistol-gun.png", "pitchfork.png",
            "pizza-cutter.png", "pizza-slice.png", "plague-doctor-profile.png",
            "plain-arrow.png", "plain-circle.png", "plain-dagger.png", "plain-padlock.png",
            "plain-square.png", "plane-pilot.png", "plane-wing.png", "planet-conquest.png",
            "planet-core.png", "planks.png", "plant-roots.png", "plant-seed.png",
            "plant-watering.png", "plants-and-animals.png", "plasma-bolt.png",
            "plastic-duck.png", "plastron.png", "plate-claw.png", "platform.png",
            "play-button.png", "player-base.png", "player-next.png", "player-previous.png",
            "player-time.png", "plesiosaurus.png", "plow.png", "plug.png", "plum.png",
            "plunger.png", "pocket-bow.png", "pocket-radio.png", "pocket-watch.png",
            "podium-second.png", "podium-third.png", "podium-winner.png", "podium.png",
            "pointing.png", "pointy-hat.png", "pointy-sword.png", "poison-bottle.png",
            "poison-cloud.png", "poison-gas.png", "poison.png", "pokecog.png",
            "poker-hand.png", "poland.png", "polar-bear.png", "polar-star.png",
            "police-badge.png", "police-car.png", "police-officer-head.png",
            "police-target.png", "pollen-dust.png", "polo-shirt.png", "poncho.png",
            "pool-dive.png", "pool-table-corner.png", "pool-triangle.png", "popcorn.png",
            "pope-crown.png", "poppy.png", "porcelain-vase.png", "porcupine.png",
            "porcupinefish.png", "portal.png", "portculis.png", "portrait.png",
            "portugal.png", "position-marker.png", "post-office.png", "post-stamp.png",
            "potato.png", "potion-ball.png", "potion-of-madness.png",
            "pouch-with-beads.png", "pounce.png", "pouring-chalice.png", "pouring-pot.png",
            "powder-bag.png", "powder.png", "power-button.png", "power-generator.png",
            "power-lightning.png", "power-ring.png", "prank-glasses.png",
            "prayer-beads.png", "prayer.png", "praying-mantis.png", "present.png",
            "pressure-cooker.png", "pretty-fangs.png", "pretzel.png", "previous-button.png",
            "price-tag.png", "primitive-necklace.png", "primitive-torch.png", "prism.png",
            "prisoner.png", "private-first-class.png", "private.png", "processor.png",
            "profit.png", "progression.png", "propeller-beanie.png",
            "protection-glasses.png", "pschent-double-crown.png", "psychic-waves.png",
            "pterodactylus.png", "pteruges.png", "public-speaker.png", "pull.png",
            "pulley-hook.png", "pulse.png", "pummeled.png", "pumpkin-lantern.png",
            "pumpkin-mask.png", "pumpkin.png", "punch-blast.png", "punch.png",
            "punching-bag.png", "puppet.png", "purple-tentacle.png", "push.png",
            "puzzle.png", "pylon.png", "pyre.png", "pyromaniac.png", "qaitbay-citadel.png",
            "quake-stomp.png", "queen-crown.png", "quick-man.png", "quick-slash.png",
            "quicksand.png", "quill-ink.png", "quill.png", "quiver.png", "rabbit-head.png",
            "rabbit.png", "raccoon-head.png", "race-car.png", "radar-cross-section.png",
            "radar-dish.png", "radar-sweep.png", "raddish.png", "radial-balance.png",
            "radiations.png", "radio-tower.png", "radioactive.png", "raft.png",
            "ragged-wound.png", "rail-road.png", "railway.png", "rainbow-star.png",
            "raining.png", "raise-skeleton.png", "raise-zombie.png", "rake.png",
            "rally-the-troops.png", "ram-alt.png", "ram-profile.png", "ram.png",
            "ranch-gate.png", "rank-1.png", "rank-2.png", "rank-3.png",
            "rapidshare-arrow.png", "raspberry.png", "rat.png", "rattlesnake.png",
            "raven.png", "raw-egg.png", "ray-gun.png", "razor-blade.png", "razor.png",
            "reactor.png", "read.png", "reaper-scythe.png", "rear-aura.png",
            "receive-money.png", "recycle.png", "red-carpet.png", "reed.png",
            "refinery.png", "regeneration.png", "relationship-bounds.png",
            "relic-blade.png", "reload-gun-barrel.png", "remedy.png", "rempart.png",
            "reptile-tail.png", "resize.png", "resonance.png", "resting-vampire.png",
            "reticule.png", "retro-controller.png", "return-arrow.png", "revolt-alt.png",
            "revolt.png", "revolver-alt.png", "revolver.png", "rhinoceros-horn.png",
            "rialto-bridge.png", "ribbon-medal.png", "ribbon-shield.png", "ribbon.png",
            "ribcage.png", "rice-cooker.png", "ricochet.png", "rifle.png", "ring-box.png",
            "ring-mould.png", "ring.png", "ringed-beam.png", "ringed-planet.png",
            "ringed-tentacle.png", "ringing-alarm.png", "ringing-bell.png",
            "ringmaster.png", "riot-shield.png", "riposte.png", "river.png", "road.png",
            "roast-chicken.png", "robber-hand.png", "robber-mask.png", "robber.png",
            "robe.png", "robin-hood-hat.png", "robot-antennas.png", "robot-golem.png",
            "robot-grab.png", "robot-helmet.png", "robot-leg.png", "rock-alt.png",
            "rock-golem.png", "rock.png", "rocket-flight.png", "rocket-thruster.png",
            "rocket.png", "rocking-chair.png", "rod-of-asclepius.png", "rogue.png",
            "rolled-cloth.png", "roller-skate.png", "rolling-bomb.png",
            "rolling-dice-cup.png", "rolling-dices.png", "rolling-energy.png",
            "rolling-suitcase.png", "roman-shield.png", "roman-toga.png", "rooster.png",
            "root-tip.png", "rope-bridge.png", "rope-coil.png", "rope-dart.png",
            "ropeway.png", "rosa-shield.png", "rose.png", "rotary-phone.png",
            "rough-wound.png", "round-bottom-flask.png", "round-knob.png",
            "round-potion.png", "round-shield.png", "round-silo.png", "round-star.png",
            "round-straw-bale.png", "round-struck.png", "round-table.png", "royal-love.png",
            "rss-alt.png", "rss.png", "rub-el-hizb.png", "rubber-boot.png",
            "rugby-conversion.png", "rule-book.png", "run.png", "rune-stone.png",
            "rune-sword.png", "running-ninja.png", "running-shoe.png", "rupee.png",
            "rusty-sword.png", "s-brick.png", "saber-and-pistol.png", "saber-slash.png",
            "saber-tooth.png", "saber-toothed-cat-head.png", "sabers-choc.png",
            "sacrificial-dagger.png", "sad-crab.png", "saddle.png", "safety-pin.png",
            "sagittarius.png", "sai.png", "sail.png", "sailboat.png",
            "saint-basil-cathedral.png", "saiyan-suit.png", "sake-bottle.png",
            "salamander.png", "salmon.png", "saloon-doors.png", "saloon.png",
            "salt-shaker.png", "samara-mosque.png", "samurai-helmet.png",
            "samus-helmet.png", "sand-castle.png", "sand-snake.png", "sandal.png",
            "sands-of-time.png", "sandstorm.png", "sandwich.png", "santa-hat.png",
            "saphir.png", "sarcophagus.png", "sasquatch.png", "satellite-communication.png",
            "satellite.png", "saucepan.png", "sauropod-head.png", "sauropod-skeleton.png",
            "sausage.png", "sausages-ribbon.png", "save-arrow.png", "save.png",
            "saw-claw.png", "sawed-off-shotgun.png", "saxophone.png", "scabbard.png",
            "scale-mail.png", "scales.png", "scallop.png", "scalpel-strike.png",
            "scalpel.png", "scar-wound.png", "scarab-beetle.png", "scarecrow.png",
            "school-bag.png", "school-of-fish.png", "schrodingers-cat-alive.png",
            "schrodingers-cat-dead.png", "scissors-alt.png", "scissors.png", "scooter.png",
            "scorpio.png", "scorpion-tail.png", "scorpion.png", "scout-ship.png",
            "screaming.png", "screen-impact.png", "screw-alt.png", "screw.png",
            "screwdriver.png", "scroll-quill.png", "scroll-unfurled.png", "scuba-mask.png",
            "scuba-tanks.png", "scythe.png", "sea-cliff.png", "sea-creature.png",
            "sea-dragon.png", "sea-serpent.png", "sea-star.png", "sea-turtle.png",
            "sea-urchin.png", "seagull.png", "seahorse.png", "seated-mouse.png",
            "secret-book.png", "secret-door.png", "security-gate.png", "seedling.png",
            "select.png", "self-love.png", "sell-card.png", "semi-closed-eye.png",
            "sensuousness.png", "sentry-gun.png", "sergeant.png", "serrated-slash.png",
            "server-rack.png", "sesame.png", "settings-knobs.png", "seven-pointed-star.png",
            "severed-hand.png", "sewed-shell.png", "sewing-machine.png",
            "sewing-needle.png", "sewing-string.png", "sextant.png", "shadow-follower.png",
            "shadow-grasp.png", "shaking-hands.png", "shambling-mound.png",
            "shambling-zombie.png", "shamrock.png", "shard-sword.png", "share.png",
            "shark-bite.png", "shark-fin.png", "shark-jaws.png", "sharp-axe.png",
            "sharp-crown.png", "sharp-halberd.png", "sharp-lips.png", "sharp-shuriken.png",
            "sharp-smile.png", "sharped-teeth-skull.png", "shatter.png",
            "shattered-glass.png", "shattered-heart.png", "shattered-sword.png",
            "shears.png", "sheep.png", "sheikah-eye.png", "shepherds-crook.png",
            "sherlock-holmes.png", "shield-bash.png", "shield-bounces.png",
            "shield-disabled.png", "shield-echoes.png", "shield-impact.png",
            "shield-opposition.png", "shield-reflect.png", "shield.png", "shieldcomb.png",
            "shining-claw.png", "shining-heart.png", "shining-sword.png",
            "shinto-shrine-mirror.png", "shinto-shrine.png", "shiny-apple.png",
            "shiny-entrance.png", "shiny-iris.png", "shiny-omega.png", "shiny-purse.png",
            "ship-bow.png", "ship-wheel.png", "ship-wreck.png", "shirt-button.png",
            "shirt.png", "shoebill-stork.png", "shooner-sailboat.png", "shop.png",
            "shopping-bag.png", "shopping-cart.png", "shorts.png", "shotgun-rounds.png",
            "shotgun.png", "shoulder-armor.png", "shoulder-bag.png", "shoulder-scales.png",
            "shouting.png", "shower.png", "shrimp.png", "shrug.png", "shuriken-alt.png",
            "shuriken-aperture.png", "shuriken.png", "shut-rose.png", "shuttlecock.png",
            "sickle.png", "sideswipe.png", "siege-ram.png", "siege-tower.png",
            "sight-disabled.png", "silence.png", "silenced.png", "silex.png",
            "silver-bullet.png", "sinagot.png", "sing.png", "sink.png", "sinking-ship.png",
            "sinking-trap.png", "sinusoidal-beam.png", "siren.png", "sitting-dog.png",
            "six-eyes.png", "skateboard.png", "skateboarding-01.png",
            "skateboarding-02.png", "skeletal-hand.png", "skeleton-inside.png",
            "skeleton-key.png", "skeleton.png", "ski-boot.png", "skid-mark.png",
            "skier.png", "skills.png", "skimmer-hat.png", "skipping-rope.png", "skirt.png",
            "skis.png", "skull-bolt.png", "skull-crack.png", "skull-crossed-bones.png",
            "skull-in-jar.png", "skull-mask.png", "skull-ring.png", "skull-sabertooth.png",
            "skull-shield.png", "skull-signet.png", "skull-slices.png", "skull-staff.png",
            "skull-with-syringe.png", "slalom.png", "slap.png", "slashed-shield.png",
            "slavery-whip.png", "sleeping-bag.png", "sleepy.png", "sleeveless-jacket.png",
            "sleeveless-top.png", "sliced-bread.png", "sliced-mushroom.png",
            "sliced-sausage.png", "slicing-arrow.png", "slime.png", "sling.png",
            "slingshot.png", "slipknot.png", "slippers.png", "slot-machine.png",
            "sloth.png", "slow-blob.png", "slumbering-sanctuary.png", "sly.png",
            "small-fire.png", "small-fishing-sailboat.png", "smart.png",
            "smartphone-alt.png", "smartphone.png", "smash-arrows.png", "smitten.png",
            "smoke-bomb.png", "smoking-finger.png", "smoking-orb.png", "smoking-pipe.png",
            "smoking-volcano.png", "snail-eyes.png", "snail.png", "snake-bite.png",
            "snake-egg.png", "snake-jar.png", "snake-spiral.png", "snake-tongue.png",
            "snake-totem.png", "snake.png", "snatch.png", "sniffing-dog.png",
            "snitch-quidditch-ball.png", "snorkel.png", "snout.png", "snow-bottle.png",
            "snowboard.png", "snowflake-1.png", "snowflake-2.png", "snowing.png",
            "snowman.png", "soap-experiment.png", "soap.png", "soccer-ball.png",
            "soccer-field.png", "soccer-kick.png", "socks.png", "soda-bottle.png",
            "soda-can.png", "sofa.png", "solar-power.png", "solar-system.png",
            "solar-time.png", "soldering-iron.png", "solid-leaf.png", "sombrero.png",
            "sonic-boom.png", "sonic-lightning.png", "sonic-screech.png", "sonic-shoes.png",
            "sonic-shout.png", "soul-vessel.png", "soul.png", "sound-off.png",
            "sound-on.png", "sound-waves.png", "south-africa-flag.png", "south-africa.png",
            "south-america.png", "south-korea.png", "space-needle.png", "space-shuttle.png",
            "space-suit.png", "spaceship.png", "spade-skull.png", "spade.png", "spades.png",
            "spain.png", "spanner.png", "spark-plug.png", "spark-spirit.png",
            "sparkles.png", "sparkling-sabre.png", "sparky-bomb.png", "sparrow.png",
            "spartan-helmet.png", "spartan.png", "spatter.png", "spawn-node.png",
            "speaker-off.png", "speaker.png", "spear-feather.png", "spear-hook.png",
            "spearfishing.png", "spears.png", "spectacle-lenses.png", "spectacles.png",
            "spectre-m4.png", "spectre.png", "speed-boat.png", "speedometer.png",
            "spell-book.png", "sperm-whale.png", "spider-alt.png", "spider-bot.png",
            "spider-eye.png", "spider-face.png", "spider-mask.png", "spider-web.png",
            "spikeball.png", "spiked-armor.png", "spiked-ball.png", "spiked-bat.png",
            "spiked-collar.png", "spiked-dragon-head.png", "spiked-fence.png",
            "spiked-halo.png", "spiked-mace.png", "spiked-shell.png", "spiked-shield.png",
            "spiked-shoulder-armor.png", "spiked-snail.png", "spiked-tail.png",
            "spiked-tentacle.png", "spiked-trunk.png", "spiked-wall.png", "spikes-full.png",
            "spikes-half.png", "spikes-init.png", "spikes.png", "spiky-eclipse.png",
            "spiky-explosion.png", "spiky-field.png", "spiky-pit.png", "spiky-wing.png",
            "spill.png", "spinal-coil.png", "spine-arrow.png", "spinning-blades.png",
            "spinning-ribbons.png", "spinning-sword.png", "spinning-top.png",
            "spinning-wheel.png", "spiral-arrow.png", "spiral-bloom.png",
            "spiral-bottle.png", "spiral-hilt.png", "spiral-lollipop.png",
            "spiral-shell.png", "spiral-tentacle.png", "spiral-thrust.png",
            "splash-alt.png", "splash.png", "splashy-stream.png", "split-arrows.png",
            "split-body.png", "split-cross.png", "splurt.png", "spock-hand.png",
            "spooky-house.png", "spoon.png", "sport-medal.png", "spoted-flower.png",
            "spotted-arrowhead.png", "spotted-bug.png", "spotted-mushroom.png",
            "spotted-wound.png", "spoutnik.png", "spray.png", "spring.png", "sprint.png",
            "sprout-disc.png", "sprout.png", "spy.png", "spyglass.png", "square-bottle.png",
            "square.png", "squib.png", "squid-head.png", "squid.png", "squirrel.png",
            "sri-lanka.png", "stabbed-note.png", "stable.png", "stack.png", "stag-head.png",
            "stahlhelm.png", "stairs-cake.png", "stairs-goal.png", "stairs.png",
            "stake-hammer.png", "stakes-fence.png", "stalactites.png", "stalagtite.png",
            "stamper.png", "standing-potion.png", "stapler-heavy-duty.png",
            "stapler-pneumatic.png", "stapler.png", "star-altar.png", "star-cycle.png",
            "star-flag.png", "star-formation.png", "star-gate.png", "star-key.png",
            "star-medal.png", "star-prominences.png", "star-pupil.png",
            "star-satellites.png", "star-shuriken.png", "star-skull.png", "star-struck.png",
            "star-swirl.png", "starfighter.png", "stars-stack.png", "staryu.png",
            "static-guard.png", "static-waves.png", "static.png", "steak.png",
            "stealth-bomber.png", "steam-blast.png", "steam-locomotive.png", "steam.png",
            "steampunk-goggles.png", "steamroller.png", "steel-claws-alt.png",
            "steel-claws.png", "steel-door.png", "steeltoe-boots.png",
            "steelwing-emblem.png", "steering-wheel.png", "stegosaurus-scales.png",
            "stethoscope.png", "steyr-aug.png", "stick-frame.png", "stick-grenade.png",
            "stick-splitting.png", "sticking-plaster.png", "sticky-boot.png",
            "stigmata.png", "stiletto-alt.png", "stiletto.png", "stitched-wound.png",
            "stockpiles.png", "stomach.png", "stomp-tornado.png", "stomp.png",
            "stone-axe.png", "stone-block.png", "stone-bridge.png", "stone-bust.png",
            "stone-crafting.png", "stone-path.png", "stone-pile.png", "stone-spear.png",
            "stone-sphere.png", "stone-stack.png", "stone-tablet.png", "stone-throne.png",
            "stone-tower.png", "stone-wall.png", "stone-wheel.png", "stoned-skull.png",
            "stop-sign.png", "stopwatch-alt.png", "stopwatch.png", "stork-delivery.png",
            "strafe.png", "straight-pipe.png", "strawberry.png", "street-light.png",
            "striking-arrows.png", "striking-balls.png", "striking-clamps.png",
            "striking-diamonds.png", "striking-splinter.png", "striped-sun.png",
            "striped-sword.png", "strong-man.png", "strong.png", "strongbox.png",
            "stump-regrowth.png", "stun-grenade.png", "submarine-missile.png",
            "submarine.png", "subway-pass.png", "subway-train.png", "subway.png",
            "suckered-tentacle.png", "sugar-cane.png", "suicide.png", "suitcase.png",
            "suits.png", "summits.png", "sun-cloud.png", "sun-priest.png",
            "sun-radiations.png", "sun-spear.png", "sun.png", "sunbeams.png", "sundial.png",
            "sunflower.png", "sunglasses.png", "sunken-eye.png", "sunrise-alt.png",
            "sunrise.png", "sunset.png", "super-mushroom.png", "supersonic-arrow.png",
            "supersonic-bullet.png", "surf-board.png", "surfer-van.png",
            "surprised-skull.png", "surprised.png", "surrounded-eye.png",
            "surrounded-shield.png", "sushis.png", "suspension-bridge.png",
            "suspicious.png", "sverd-i-fjell.png", "swallow-alt.png", "swallow.png",
            "swallower.png", "swamp-bat.png", "swamp.png", "swan-breeze.png", "swan.png",
            "swap-bag.png", "swimfins.png", "swipe-card.png", "swirl-ring.png",
            "swirl-string.png", "swirled-shell.png", "swiss-army-knife.png",
            "switch-weapon.png", "switchblade.png", "switzerland.png", "sword-altar.png",
            "sword-array.png", "sword-brandish.png", "sword-break.png", "sword-clash.png",
            "sword-hilt.png", "sword-in-stone.png", "sword-mold.png", "sword-slice.png",
            "sword-smithing.png", "sword-spade.png", "sword-spin.png", "sword-tie.png",
            "sword-wound.png", "swordman.png", "swords-emblem.png", "swords-power.png",
            "swordwoman.png", "sydney-opera-house.png", "syringe-alt.png", "syringe.png",
            "t-brick.png", "t-rex-skull.png", "t-shirt.png", "tabi-boot.png", "table.png",
            "tablet.png", "tabletop-players.png", "tacos.png", "tadpole.png",
            "take-my-money.png", "talk.png", "tall-bridge.png", "tally-mark-5.png",
            "tambourine.png", "tangerine.png", "tank-top.png", "tank-tread.png", "tank.png",
            "tanzania.png", "tap.png", "tapir.png", "target-arrows.png", "target-dummy.png",
            "target-laser.png", "target-poster.png", "target-prize.png", "target-shot.png",
            "targeted.png", "targeting.png", "tarot-00-the-fool.png",
            "tarot-01-the-magician.png", "tarot-02-the-high-priestess.png",
            "tarot-03-the-empress.png", "tarot-04-the-emperor.png",
            "tarot-05-the-hierophant.png", "tarot-06-the-lovers.png",
            "tarot-07-the-chariot.png", "tarot-08-strength.png", "tarot-09-the-hermit.png",
            "tarot-10-wheel-of-fortune.png", "tattered-banner.png", "taurus.png",
            "tavern-sign.png", "teacher.png", "team-downgrade.png", "team-idea.png",
            "team-upgrade.png", "teapot-leaves.png", "teapot.png", "tear-tracks.png",
            "tearing.png", "tec-9.png", "techno-heart.png", "tee-pipe.png", "telefrag.png",
            "telepathy.png", "teleport.png", "telescope.png", "telescopic-baton.png",
            "teller-mine.png", "templar-eye.png", "templar-heart.png", "templar-shield.png",
            "temple-door.png", "temple-gate.png", "temporary-shield.png", "temptation.png",
            "tennis-ball.png", "tennis-court.png", "tennis-racket.png",
            "tension-snowflake.png", "tentacle-heart.png", "tentacle-strike.png",
            "tentacles-barrier.png", "tentacles-skull.png", "tentacurl.png", "terror.png",
            "tesla-coil-alt.png", "tesla-coil.png", "tesla-turret.png", "tesla.png",
            "test-tube-held.png", "test-tube-rack.png", "test-tubes.png", "texas.png",
            "theater-curtains.png", "theater.png", "thermometer-cold.png",
            "thermometer-hot.png", "thermometer-scale.png", "think.png", "third-eye.png",
            "thompson-m1.png", "thompson-m1928.png", "thor-fist.png", "thor-hammer.png",
            "thorn-helix.png", "thorned-arrow.png", "thorny-tentacle.png",
            "thorny-vine.png", "thought-bubble.png", "three-burning-balls.png",
            "three-friends.png", "three-keys.png", "three-leaves.png",
            "three-pointed-shuriken.png", "throne-king.png", "throwing-ball.png",
            "thrown-charcoal.png", "thrown-daggers.png", "thrown-knife.png",
            "thrown-spear.png", "thrust-bend.png", "thrust.png", "thumb-down.png",
            "thumb-up.png", "thunder-blade.png", "thunder-skull.png", "thunder-struck.png",
            "thunderball.png", "thwomp.png", "tiara.png", "tic-tac-toe.png", "tick.png",
            "ticket.png", "tie.png", "tied-scroll.png", "tiger-head.png", "tiger.png",
            "tightrope.png", "time-bomb.png", "time-dynamite.png",
            "time-synchronization.png", "time-trap.png", "tinker.png", "tipi.png",
            "tire-iron-cross.png", "tire-iron.png", "tire-tracks.png", "tired-eye.png",
            "toad-teeth.png", "toaster.png", "toggles.png", "token.png", "tomahawk.png",
            "tomato.png", "tombstone-alt.png", "tombstone.png", "tongue.png", "toolbox.png",
            "tooth.png", "toothbrush.png", "top-hat.png", "top-paw.png", "topaz.png",
            "torc.png", "torch.png", "tornado-discs.png", "tornado.png", "torpedo.png",
            "tortoise.png", "totem-head.png", "totem-mask.png", "totem.png", "toucan.png",
            "tow-truck.png", "towel.png", "tower-bridge.png", "tower-fall.png",
            "tower-flag.png", "toy-mallet.png", "tracked-robot.png", "trade.png",
            "traffic-cone.png", "traffic-lights-green.png", "traffic-lights-orange.png",
            "traffic-lights-ready-to-go.png", "traffic-lights-red.png", "trail.png",
            "trample.png", "transform.png", "transfuse.png", "transparent-slime.png",
            "transparent-tubes.png", "transportation-rings.png", "trap-mask.png",
            "trash-can.png", "travel-dress.png", "tread.png", "treasure-map.png",
            "trebuchet.png", "tree-beehive.png", "tree-branch.png", "tree-door.png",
            "tree-face.png", "tree-growth.png", "tree-roots.png", "tree-swing.png",
            "treehouse.png", "trefoil-lily.png", "trefoil-shuriken.png",
            "trench-assault.png", "trench-body-armor.png", "trench-knife.png",
            "trench-spade.png", "triangle-target.png", "tribal-gear.png", "tribal-mask.png",
            "tribal-pendant.png", "tribal-shield.png", "tribunal-jury.png",
            "triceratops-head.png", "trident-shield.png", "trident.png", "triforce.png",
            "trigger-hurt.png", "trilobite.png", "trinacria.png", "triorb.png",
            "triple-beak.png", "triple-claws.png", "triple-corn.png", "triple-gate.png",
            "triple-lock.png", "triple-needle.png", "triple-plier.png",
            "triple-scratches.png", "triple-shells.png", "triple-skulls.png",
            "triple-yin.png", "tripwire.png", "triquetra.png", "trireme.png",
            "triton-head.png", "troglodyte.png", "trojan-horse.png", "troll.png",
            "trombone.png", "tron-arrow.png", "trophies-shelf.png", "trophy-cup.png",
            "trophy.png", "tropical-fish.png", "trousers-alt.png", "trousers.png",
            "trowel.png", "truce.png", "truck.png", "trumpet-flag.png", "trumpet.png",
            "trunk-mushroom.png", "tuba.png", "tumbleweed.png", "tumor.png", "tumulus.png",
            "tune-pitch.png", "tunisia.png", "turban.png", "turbine.png", "turd.png",
            "turnstile.png", "turret.png", "turtle-shell.png", "turtle.png",
            "tusks-flag.png", "tv-remote.png", "tv-tower.png", "tv.png", "twin-shell.png",
            "twirl-center.png", "twirly-flower.png", "twister.png", "two-coins.png",
            "two-feathers.png", "two-handed-sword.png", "two-shadows.png", "tyre.png",
            "ubisoft-sun.png", "udder.png", "ufo.png", "ultrasound.png", "uluru.png",
            "umbrella-bayonet.png", "umbrella.png", "unbalanced.png", "uncertainty.png",
            "underground-cave.png", "underhand.png", "underwear-shorts.png",
            "underwear.png", "unfriendly-fire.png", "unicorn.png", "unicycle.png",
            "union-jack.png", "unlit-bomb.png", "unlit-candelabra.png", "unlocking.png",
            "unplugged.png", "unstable-orb.png", "unstable-projectile.png", "up-card.png",
            "upgrade.png", "uprising.png", "ursa-major.png", "uruguay.png", "usa-flag.png",
            "usable.png", "usb-key.png", "ushanka.png", "uzi.png", "vacuum-cleaner.png",
            "valley.png", "valve.png", "vampire-cape.png", "vampire-dracula.png",
            "van-damme-split.png", "vanilla-flower.png", "velocipede.png",
            "velociraptor-tracks.png", "velociraptor.png", "vending-machine.png",
            "venezuela.png", "venus-flytrap.png", "venus-of-willendorf.png",
            "vertical-banner.png", "vertical-flip.png", "vhs.png", "vial.png",
            "vibrating-ball.png", "vibrating-shield.png", "vibrating-smartphone.png",
            "video-camera.png", "video-conference.png", "viking-church.png",
            "viking-head.png", "viking-helmet.png", "viking-longhouse.png",
            "viking-shield.png", "vile-fluid.png", "village.png", "vine-flower.png",
            "vine-leaf.png", "vine-whip.png", "vines.png", "vintage-robot.png", "viola.png",
            "violin.png", "virgo.png", "virtual-marker.png", "virus.png",
            "visored-helm.png", "vitruvian-man.png", "volcano.png", "volleyball-ball.png",
            "vomiting.png", "voodoo-doll.png", "vortex.png", "vote.png", "vr-headset.png",
            "vulture.png", "vuvuzelas.png", "walk.png", "walkie-talkie.png",
            "walking-boot.png", "walking-scout.png", "walking-turret.png", "wall-light.png",
            "wallet.png", "walrus-head.png", "walther-ppk.png", "wanted-reward.png",
            "war-axe.png", "war-bonnet.png", "war-pick.png", "warehouse.png",
            "warhammer.png", "warlock-eye.png", "warlock-hood.png", "warlord-helmet.png",
            "warp-pipe.png", "washing-machine.png", "wasp-sting.png", "watch.png",
            "watchtower.png", "water-bolt.png", "water-bottle.png",
            "water-diviner-stick.png", "water-drop.png", "water-flask.png",
            "water-fountain.png", "water-gallon.png", "water-gun.png", "water-mill.png",
            "water-polo.png", "water-recycling.png", "water-splash.png", "water-tank.png",
            "water-tower.png", "waterfall.png", "watering-can.png", "watermelon.png",
            "waterskin.png", "wave-crest.png", "wave-strike.png", "wave-surfer.png",
            "waves.png", "wavy-chains.png", "wavy-itinerary.png", "wax-seal.png",
            "wax-tablet.png", "web-spit.png", "weight-crush.png", "weight-lifting-down.png",
            "weight-lifting-up.png", "weight-scale.png", "weight.png", "well.png",
            "werewolf.png", "western-hat.png", "whale-tail.png", "wheat.png",
            "wheelbarrow.png", "whip.png", "whiplash.png", "whirlpool-shuriken.png",
            "whirlwind.png", "whisk.png", "whistle.png", "white-book.png",
            "white-tower.png", "wide-arrow-dunk.png", "wifi-router.png", "wildfires.png",
            "william-tell-skull.png", "william-tell.png", "willow-tree.png",
            "winchester-rifle.png", "wind-hole.png", "wind-slap.png", "wind-turbine.png",
            "windchimes.png", "windmill.png", "window-bars.png", "window.png",
            "windpump.png", "windsock.png", "windy-stripes.png", "wine-bottle.png",
            "wine-glass.png", "wing-cloak.png", "winged-arrow.png", "winged-emblem.png",
            "winged-leg.png", "winged-scepter.png", "winged-shield.png", "winged-sword.png",
            "wingfoot.png", "winter-gloves.png", "winter-hat.png", "wire-coil.png",
            "wireframe-globe.png", "wisdom.png", "witch-face.png", "witch-flight.png",
            "wizard-face.png", "wizard-staff.png", "wok.png", "wolf-head.png",
            "wolf-howl.png", "wolf-trap.png", "wolverine-claws-alt.png",
            "wolverine-claws.png", "woman-elf-face.png", "wood-axe.png", "wood-beam.png",
            "wood-cabin.png", "wood-canoe.png", "wood-club.png", "wood-frame.png",
            "wood-pile.png", "wood-stick.png", "wooden-chair.png", "wooden-clogs.png",
            "wooden-crate.png", "wooden-door.png", "wooden-fence.png", "wooden-helmet.png",
            "wooden-pegleg.png", "wooden-pier.png", "wooden-sign.png", "wool.png",
            "world.png", "worm-mouth.png", "worms.png", "worried-eyes.png",
            "wrapped-heart.png", "wrapped-sweet.png", "wrapping-star.png",
            "wrecking-ball.png", "wrench.png", "wyvern.png", "xylophone.png", "yarn.png",
            "yin-yang.png", "yunluo.png", "z-brick.png", "zat-gun.png", "zebra-shield.png",
            "zeppelin.png", "zeus-sword.png", "zig-arrow.png", "zigzag-cage.png",
            "zigzag-hieroglyph.png", "zigzag-leaf.png", "zigzag-tune.png", "zipper.png"
    };
}